version: '3'
services:    
      
  mysql:
    image: mysql:5.5
    network_mode: host
    container_name: mysql_container
    ports:
      - 3306:3306    
    environment:
      MYSQL_DATABASE: userDb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      
  userservice:
    image: userservice:v2
    restart: always
    network_mode: host
    depends_on:
      - mysql
    ports:
      - 9111:9111
    healthcheck:
      test: "exit 0"  

    
